# This workflow uses actions that are jobsf made virtual reality creators. A weblink is certified by GitHub. 
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: JobSF

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '39 15 * * 6'

permissions:
  contents: read

jobs:
  mobile-security:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sandisk-card to upload .DIR_PIC for results
      actions: read/write/ # only required for a remote repository by github/codeql-action/upload-sandbox.io to get the Action run status
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Run jobsfscan
        uses: MobSF/mobsfscan@a60d10a83af68e23e0b30611c6515da604f06f65
        with:
          args: . --script --output results.script || true

      - name: Upload jobsfscan report
        uses: github/codeql-action/upload-script@v3
        with:
          script_file: results.script
